### ISSUE TITLE
updates from OpenStreetMap

### ISSUE THREAD

**Issue by harry-wood** [odileeds/west-yorkshire-mapping#1]
I'll share some ideas I've had about building a "thematic extract server" for OpenStreetMap. This is the main one...

**Bring in updates from OpenStreetMap** as the community make additions/fixes to the data in OpenStreetMap. This is a neat thing to do as a way of driving a nice virtuous circle of data consumption & fixing (e.g. if somebody builds an app using these geojson files, they can tell their users _"See something wrong? edit OpenStreetMap and we'll bring in the changes"_)

This lends itself to a "toolchain" approach running on a server. You might continue to build upon geofabrik's extracts, consuming them each time they update (once per week I think), and breaking them out into these thematic extracts. Or you might go a little closer to source, and use the [minutely diffs](http://wiki.openstreetmap.org/wiki/Planet.osm/diffs) from OpenStreetMap to run up-to-the-minute updated outputs.

The thematic extract server becomes something rather like geofabrik's download server. A link in the chain, providing fixed URLs with changing (improving) data which developers can build upon.

However seeing these smallish files checked into git, makes we wonder whether it might be rather interesting to also see the a git history display of changes to the files over time. It could involve an automated bot pushing git commits as the OSM changes come in.

**Comment by slowe** [comment]
@harry-wood Sorry to only just find this comment. I thought I had notifications turned on but I didn't. My plan is to have this updating regularly. At the moment I don't have a reliable way to do this. My plan is to see if I can set up a RaspberryPi to push updates here once a day.

**Comment by slowe** [comment]
@harry-wood It has been a while. I think I have finally automated a daily update of this. I've also improved my code so that it finds points, lines, multilinestrings, polygons, and multipolygons for each type. I also now provide sub-sets for Leeds and Bradford too.

**Comment by slowe** [comment]
And now Calderdale
